version: "3.8"

services:
  apacheignite:
    image: apacheignite/ignite
    container_name: apacheignite
    ports:
      - "10800:10800"
  surrealdb:
    entrypoint:
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
  supabasedb:
    image: supabase/postgres
    ports:
    - 5433:5432
    command: postgres -c config_file=/etc/postgressql/postgressql.conf
    environment:
      POSTGRES_PASSWROD: postgres
  couchbase:
    image: couchbase
    container_name: db
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11207:11207"
      - "11210:11210"
      - "11280:11280"
      - "18091-18097:18091-18097"
    # Add other configuration options as needed
    # For example, to set environment variables:
    environment:
      - COUCHBASE_ROOT_PASSWORD=admin
  # Add more services below as required
  # Example service:
  # service_name:
  #   image: image_name:tag
  #   container_name: container_name
  #   ports:
  #     - "host_port:container_port"
  #   volumes:
  #     - "volume_name:/path/in/container"
  #   environment:
  #     - ENV_VARIABLE=value
  #   ...

# Add any additional configuration for the whole Docker Compose stack here if needed
# For example, defining volumes, networks, etc.
