version: "3.8"

services:
  apacheignite:
    image: apacheignite/ignite
    container_name: apacheignite
    ports:
      - "10800:10800"
  surrealdb:
    entrypoint:
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000

  # Add more services below as required
  # Example service:
  # service_name:
  #   image: image_name:tag
  #   container_name: container_name
  #   ports:
  #     - "host_port:container_port"
  #   volumes:
  #     - "volume_name:/path/in/container"
  #   environment:
  #     - ENV_VARIABLE=value
  #   ...

# Add any additional configuration for the whole Docker Compose stack here if needed
# For example, defining volumes, networks, etc.
