name: MindsDB Cloud Tests

on:
  # Triggers the workflow every day at 1 and 13:00 UTC
  schedule:
    - cron:  '0 3,15 * * *'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run MindsDB Cloud tests
      env:
        INTEGRATIONS_CONFIG: ${{ secrets.INTEGRATIONS_CONFIG }}
      run: |
        source venv/bin/activate
        python -m unittest discover -s cloud_sql_api
        python -m unittest discover -s cloud_mongo_api
        python -m unittest discover -s health_checks
        python -m unittest discover -s integrations/ml/
        python -m unittest integrations/test_mysql.py
        python -m unittest integrations/test_postgresql.py 
        python -m unittest integrations/test_clickhouse.py 
